---

development: &default
  secret_key_base: <%= ENV['SECRET_TOKEN'] || (ENV['RAILS_ENV'] == 'production' ? raise('Set SECRET_TOKEN env variable') : 'a'*30) %>

test:
  <<: *default

production:
  <<: *default
