# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14e332a459dc6216bc20c061ee9dc5441073f428803287f8e2736ec36c604e7f0cb00971eb0015b899710e1f0e410ef0373cf7db73d1e0a95f9b4416d6302824

test:
  secret_key_base: 195bf3ab3344f7a27d630ffa2f18cc7241f25bf4a3355ff031b572b68279a7c4ce30bb34a3be06a050ee727435cf43d565d86ea93ed533551f0a8fc4ad8e1669

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
